#!/usr/bin/env python

def replaceSpace(str_):
    charlist = []
    for char in str_:
        if char == ' ':
            char = '%20'
        charlist.append(char)
    return ''.join(charlist)

def replaceSpaceWithSplit(str_):
    return '%20'.join(str_.split())

#testing

if __name__ == '__main__':
    strings = ['a b c d e','mmm nnn']
    for str_ in strings:
        print('replaceSpace({}): {}'.format(str_, replaceSpace(str_)))
        print('replaceSpaceWithSplit({}): {}'.format(str_, replaceSpaceWithSplit(str_)))
