#!/usr/bin/env python

def compressSimple(str_):
    charlist = []
    lastchar = ''
    count = 0
    for char in str_:
        if char == lastchar:
            count += 1
        else:
            if lastchar != '':
                charlist.append(lastchar + str(count))
            count = 1
        lastchar = char
    charlist.append(lastchar + str(count))
    result = ''.join(charlist)
    
    if len(result) < len(str_):
        return result
    else:
        return str_


#testing

if __name__ == '__main__':
    strings = ['aaabeeee','helloworld']
    for str_ in strings:
        print('compressSimple({}): {}'.format(str_, compressSimple(str_)))
