#!/usr/bin/env python

def rotateSubstring(s1, s2):
    if len(s1) != len(s2): return False
    s1s1 = s1 + s1
    return s1s1.find(s2) > -1

#testing

if __name__ == '__main__':
    if rotateSubstring('hello', 'llohe'):
        print ('Substring!')
    else:
        print ('Not a substring')
