#!/usr/bin/env python

#reverse string
def reverseString(str_):
    return str_[::-1]

#testing

if __name__ == '__main__':
    strings = ('','spam','hello','mmsdfhgjckl')
    for str_ in strings:
        print('reverseString({}): {}'.format(str_, reverseString(str_)))
